% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/E.BE.r
\name{E.BE}
\alias{E.BE}
\title{Estimation of the Population Total under Bernoulli Sampling Without Replacement}
\usage{
E.BE(y, prob)
}
\arguments{
\item{y}{Vector, matrix or data frame containing the values of the
variables of interest for every unit in the selected sample.}

\item{prob}{Scalar. The (constant) inclusion probability used in the
Bernoulli sampling design. Must satisfy \code{0 < prob <= 1}.}
}
\value{
A matrix with four rows and one column per variable of interest:
\itemize{
  \item \code{Estimation}: Estimated population total.
  \item \code{Standard Error}: Estimated standard error of the total.
  \item \code{CVE}: Estimated coefficient of variation (in percentage).
  \item \code{DEFF}: Design effect with respect to simple random sampling.
}
}
\description{
Computes the Horvitz-Thompson estimator of the population total under a
Bernoulli sampling design, where each unit in the population is independently
selected with the same inclusion probability.
}
\details{
Under Bernoulli sampling, the sample size is random. The inclusion
probability is constant and equal to \code{prob} for all units. The
variance estimator accounts for the randomness of the sample size.
}
\examples{
data('Lucy')
attach(Lucy)
N <- nrow(Lucy)
prob <- 0.1
sam  <- S.BE(N, prob)
sam  <- sam[sam != 0]
y    <- data.frame(Income = Income[sam], Employees = Employees[sam])
E.BE(y, prob)
}
\references{
Sarndal, C-E. and Swensson, B. and Wretman, J. (1992),
\emph{Model Assisted Survey Sampling}. Springer.\cr
Gutierrez, H. A. (2009), \emph{Estrategias de muestreo: Diseno de encuestas
y estimacion de parametros}. Editorial Universidad Santo Tomas.
}
\seealso{
\code{\link{S.BE}}, \code{\link{E.SI}}
}
\author{
Hugo Andres Gutierrez Rojas <hagutierrezro at gmail.com>
}
