% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/E.Beta.r
\name{E.Beta}
\alias{E.Beta}
\title{Estimation of Regression Coefficients under Simple Random Sampling Without Replacement}
\usage{
E.Beta(N, n, y, x, ck = 1, b0 = FALSE)
}
\arguments{
\item{N}{Population size.}

\item{n}{Sample size.}

\item{y}{Vector, matrix or data frame of variables of interest (response).}

\item{x}{Vector, matrix or data frame of auxiliary variables (predictors).}

\item{ck}{Optional variance-stabilising constant. Default is \code{1}
(homoscedastic model).}

\item{b0}{Logical. If \code{TRUE}, an intercept column of ones is
prepended to \code{x}. Default is \code{FALSE}.}
}
\value{
A three-dimensional array with dimensions \code{[3, P, Q]}, where
\code{P} is the number of auxiliary variables and \code{Q} is the number
of variables of interest. The three rows correspond to:
\itemize{
  \item \code{Beta estimation}: Estimated regression coefficient.
  \item \code{Standard Error}: Estimated standard error.
  \item \code{CVE}: Estimated coefficient of variation (in percentage).
}
}
\description{
Computes the weighted least squares estimator of regression coefficients
for a finite population under simple random sampling without replacement.
Both the estimated coefficients and their estimated standard errors are
returned.
}
\details{
The estimator uses a working model with weights \eqn{V = 1/(\pi_k c_k)},
where \eqn{\pi_k = n/N} under simple random sampling and \eqn{c_k} is an
optional variance-stabilising constant. The variance is estimated using
the residual-based sandwich approach of Sarndal et al. (1992).
}
\examples{
######################################################################
## Example 1: Linear models involving continuous auxiliary information
######################################################################

# Draws a simple random sample without replacement
data(Lucy)
attach(Lucy)

N <- dim(Lucy)[1]
n <- 400
sam <- S.SI(N, n)
# The information about the units in the sample 
# is stored in an object called data
data <- Lucy[sam,]
attach(data)
names(data)

########### common mean model 

estima<-data.frame(Income, Employees, Taxes)
x <- rep(1,n)
E.Beta(N, n, estima,x,ck=1,b0=FALSE)


########### common ratio model 

estima<-data.frame(Income)
x <- data.frame(Employees)
E.Beta(N, n, estima,x,ck=x,b0=FALSE)

########### Simple regression model without intercept

estima<-data.frame(Income, Employees)
x <- data.frame(Taxes)
E.Beta(N, n, estima,x,ck=1,b0=FALSE)

########### Multiple regression model without intercept

estima<-data.frame(Income)
x <- data.frame(Employees, Taxes)
E.Beta(N, n, estima,x,ck=1,b0=FALSE)

########### Simple regression model with intercept

estima<-data.frame(Income, Employees)
x <- data.frame(Taxes)
E.Beta(N, n, estima,x,ck=1,b0=TRUE)

########### Multiple regression model with intercept

estima<-data.frame(Income)
x <- data.frame(Employees, Taxes)
E.Beta(N, n, estima,x,ck=1,b0=TRUE)

###############################################################
## Example 2: Linear models with discrete auxiliary information
###############################################################

# Draws a simple random sample without replacement
data(Lucy)
attach(Lucy)

N <- dim(Lucy)[1]
n <- 400
sam <- S.SI(N,n)
# The information about the sample units is stored in an object called data
data <- Lucy[sam,]
attach(data)
names(data)
# The auxiliary information
Doma<-Domains(Level)

########### Poststratified common mean model

estima<-data.frame(Income, Employees, Taxes)
E.Beta(N, n, estima,Doma,ck=1,b0=FALSE)

########### Poststratified common ratio model

estima<-data.frame(Income, Employees)
x<-Doma*Taxes
E.Beta(N, n, estima,x,ck=1,b0=FALSE)
}
\references{
Sarndal, C-E. and Swensson, B. and Wretman, J. (1992),
\emph{Model Assisted Survey Sampling}. Springer.\cr
Gutierrez, H. A. (2009), \emph{Estrategias de muestreo: Diseno de encuestas
y estimacion de parametros}. Editorial Universidad Santo Tomas.
}
\seealso{
\code{\link{GREG.SI}}, \code{\link{E.SI}}
}
\author{
Hugo Andres Gutierrez Rojas <hagutierrezro at gmail.com>
}
