% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/E.PO.r
\name{E.PO}
\alias{E.PO}
\title{Estimation of the Population Total under Poisson Sampling Without Replacement}
\usage{
E.PO(y, Pik)
}
\arguments{
\item{y}{Vector, matrix or data frame containing the values of the
variables of interest for every unit in the selected sample.}

\item{Pik}{Vector of first-order inclusion probabilities for each unit
in the sample.}
}
\value{
A matrix with four rows and one column per variable of interest:
\itemize{
  \item \code{Estimation}: Estimated population total.
  \item \code{Standard Error}: Estimated standard error of the total.
  \item \code{CVE}: Estimated coefficient of variation (in percentage).
  \item \code{DEFF}: Design effect with respect to simple random sampling.
}
}
\description{
Computes the Horvitz-Thompson estimator of the population total under a
Poisson sampling design, where each unit is independently selected with
its own inclusion probability.
}
\details{
Under Poisson sampling, units are selected independently, so the exact
variance of the Horvitz-Thompson estimator has a simple closed form:
\eqn{V(\hat{t}) = \sum_k (1 - \pi_k)(y_k/\pi_k)^2}.
}
\examples{
data('Lucy')
attach(Lucy)
N <- nrow(Lucy)
n <- 400
Pik <- PikPPS(n, Employees)
sam <- S.PO(N, Pik)
sam <- sam[sam != 0]
y   <- data.frame(Income = Income[sam], Taxes = Taxes[sam])
E.PO(y, Pik[sam])
}
\references{
Sarndal, C-E. and Swensson, B. and Wretman, J. (1992),
\emph{Model Assisted Survey Sampling}. Springer.\cr
Gutierrez, H. A. (2009), \emph{Estrategias de muestreo: Diseno de encuestas
y estimacion de parametros}. Editorial Universidad Santo Tomas.
}
\seealso{
\code{\link{S.PO}}, \code{\link{E.piPS}}
}
\author{
Hugo Andres Gutierrez Rojas <hagutierrezro at gmail.com>
}
