% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/IkRS.r
\name{IkRS}
\alias{IkRS}
\title{Sample Membership Indicator Matrix for All Possible Sample Sizes}
\usage{
IkRS(N)
}
\arguments{
\item{N}{Population size. Recommended \code{N <= 10}.}
}
\value{
A binary matrix with \eqn{2^N} rows (one per non-empty subset, including
the empty set as the first row of zeros) and \code{N} columns. Entry
\eqn{(s, k) = 1} if unit \eqn{k} belongs to subset \eqn{s}.
}
\description{
Constructs the indicator matrix of the complete sampling support, stacking
the indicator matrices for all sample sizes from 1 to \code{N}. This
covers every possible non-empty subset of the population.
}
\details{
This function calls \code{\link{Ik}} for each possible sample size
\eqn{n = 1, \ldots, N} and stacks the results. It is intended for small
populations only (\code{N <= 10}) due to the exponential growth of the
support size.
}
\examples{
U <- c("Yves", "Ken", "Erik", "Sharon", "Leslie")
N <- length(U)
# The sample membership matrix for all sample sizes
IkRS(N)
# The first sample is a null one and the last sample is a census
}
\references{
Sarndal, C-E. and Swensson, B. and Wretman, J. (1992),
\emph{Model Assisted Survey Sampling}. Springer.\cr
Gutierrez, H. A. (2009), \emph{Estrategias de muestreo: Diseno de encuestas
y estimacion de parametros}. Editorial Universidad Santo Tomas.
}
\seealso{
\code{\link{Ik}}, \code{\link{SupportRS}}
}
\author{
Hugo Andres Gutierrez Rojas <hagutierrezro at gmail.com>
}
