% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/SupportWR.r
\name{SupportWR}
\alias{SupportWR}
\title{Sampling Support for With-Replacement Designs}
\usage{
SupportWR(N, m, ID = FALSE)
}
\arguments{
\item{N}{Population size.}

\item{m}{Number of draws (sample size with replacement).}

\item{ID}{Optional vector of population labels of length \code{N}.
If \code{FALSE} (default), integer indices are returned.}
}
\value{
A matrix with \code{choose(N+m-1, m)} rows and \code{m} columns. Each
row contains the (sorted) indices of one possible unordered outcome.
If \code{ID} is provided, population labels replace indices.
}
\description{
Enumerates all distinct unordered outcomes (multisets) of size \code{m}
drawn with replacement from a population of size \code{N}.
}
\details{
The number of distinct unordered with-replacement outcomes of size \code{m}
from \code{N} units is \eqn{\binom{N+m-1}{m}}. This is much smaller than
the \eqn{N^m} ordered outcomes. The algorithm uses a nested loop to
generate all non-decreasing sequences of length \code{m} from
\eqn{\{1, \ldots, N\}}.
}
\examples{
U <- c("Yves", "Ken", "Erik", "Sharon", "Leslie")
N <- length(U)
m <- 2
# With-replacement support
SupportWR(N, m)
SupportWR(N, m, ID = U)
y <- c(32, 34, 46, 89, 35)
SupportWR(N, m, ID = y)
}
\references{
Sarndal, C-E. and Swensson, B. and Wretman, J. (1992),
\emph{Model Assisted Survey Sampling}. Springer.\cr
Gutierrez, H. A. (2009), \emph{Estrategias de muestreo: Diseno de encuestas
y estimacion de parametros}. Editorial Universidad Santo Tomas.
}
\seealso{
\code{\link{IkWR}}, \code{\link{nk}}, \code{\link{p.WR}}
}
\author{
Hugo Andres Gutierrez Rojas <hagutierrezro at gmail.com>
}
