% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/Support.r
\name{Support}
\alias{Support}
\title{Sampling Support for Fixed-Size Without-Replacement Designs}
\usage{
Support(N, n, ID = FALSE)
}
\arguments{
\item{N}{Population size. Recommended \code{N <= 15}.}

\item{n}{Sample size.}

\item{ID}{Optional vector of population labels of length \code{N}.
If provided, labels replace integer indices in the output.
If \code{FALSE} (default), integer indices are returned.}
}
\value{
A matrix with \code{choose(N, n)} rows and \code{n} columns. Each row
contains the indices (or labels if \code{ID} is provided) of the units
in one possible sample. Samples are listed in lexicographic order.
}
\description{
Enumerates all possible samples of size \code{n} from a population of
size \code{N}, returning the complete sampling support as a matrix.
}
\details{
This function uses a combinatorial algorithm to enumerate all
\code{choose(N, n)} subsets of size \code{n} from \eqn{\{1, \ldots, N\}}.
It is intended for small populations only. For \code{N > 15} it becomes
very slow.
}
\examples{
U <- c("Yves", "Ken", "Erik", "Sharon", "Leslie")
N <- length(U)
n <- 2
# Ten possible samples of size n=2
Support(N, n)
# Labeled support
Support(N, n, ID = U)
# Support showing values of y
y <- c(32, 34, 46, 89, 35)
Support(N, n, ID = y)
}
\references{
Sarndal, C-E. and Swensson, B. and Wretman, J. (1992),
\emph{Model Assisted Survey Sampling}. Springer.\cr
Gutierrez, H. A. (2009), \emph{Estrategias de muestreo: Diseno de encuestas
y estimacion de parametros}. Editorial Universidad Santo Tomas.
}
\seealso{
\code{\link{Ik}}, \code{\link{SupportWR}}, \code{\link{SupportRS}}
}
\author{
Hugo Andres Gutierrez Rojas <hagutierrezro at gmail.com>
}
